### ISSUE TITLE
Please sign the release hashes

### ISSUE THREAD

**Issue by subz390** [Chia-Network/chia-network.github.io#125]
The release hashes only confirm that the file downloaded off the server was transfered and written locally without errors.  It does not validate the authenticity of the release file.

For reference, see how NodeJS signs it's release hashes.
https://nodejs.org/en/download/current/
https://nodejs.org/dist/v16.8.0/

1. All the release hashes are put into a text file.
https://nodejs.org/dist/v16.8.0/SHASUMS256.txt

2. That file is signed by a trusted key.
https://nodejs.org/dist/v16.8.0/SHASUMS256.txt.asc

3. End users can then verify the authenticity of the SHA256 hashes.
https://github.com/nodejs/node#verifying-binaries

4. The hashes validate the downloaded file integrity.

**Comment by hoffmang9** [comment]
Though it may look like a signature would be more valuable here - it is actually the same security as our current process.

We're not going to inject human error into the 100 CI flows and nearly 20 artifacts (in chia-blockchain) that adding a manual signature would add. We already sign the Windows and MacOS installers in that CI. The private keys in the CI have the same trust that adding another private key to sign all the sha256's would have. The hashes we generate when we generate binary artifacts are protected by both our GitHub credentials and our entirely separate other cloud credentials.

Until we get to reproducible builds, we and you have to trust that GitHub and Pypi are not themselves untrustworthy.

If that is not good enough, you always have the option of downloading the source and building it yourself.

**Comment by subz390** [comment]
Thank you for your comprehensive response, I understand.
