### ISSUE TITLE
Connecting to wallet problem

### ISSUE THREAD

**Issue by AnstasiaMia** [Chia-Network/chia-network.github.io#201]
Hello! I have this problem with connecting to the wallet, it was “connecting to wallet” phase for 3 weeks without any changes, tried it 3 times and every time it’s the same. Was deleting and reinstalling again and again and nothing works. Can u help me with that please?
I have MacOS hight sierra version 10.13.6 and trying to connect to MacOS intel wallet version 1.2.11

**Comment by hoffmang9** [comment]
Wrong repository and High Sierra is not supported.
